-- =====================================================================
-- V1 - Esquema inicial de SplitFair
--
-- Notas de diseno:
--
-- * Los importes son NUMERIC(12,2), nunca DOUBLE PRECISION. El punto
--   flotante binario no puede representar 0.10 de forma exacta, y en una
--   aplicacion contable ese error se acumula. NUMERIC es decimal exacto.
--
-- * ON DELETE CASCADE solo cuelga de la entidad propietaria: al borrar un
--   grupo desaparecen sus miembros, gastos y liquidaciones. Las FK que
--   apuntan a users son RESTRICT (por omision): un usuario con historial
--   contable no se borra sin resolver antes su situacion en cada grupo.
--
-- * Toda FK lleva indice. PostgreSQL indexa automaticamente la clave
--   primaria, pero NO el lado que referencia, y todas nuestras consultas
--   filtran por group_id o expense_id.
-- =====================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)  NOT NULL,
    email         VARCHAR(180)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMP(6)  NOT NULL,

    CONSTRAINT uk_users_email UNIQUE (email)
);

-- "groups" es palabra clave no reservada en PostgreSQL: valida como nombre
-- de tabla sin comillas. Se mantiene el nombre de la especificacion.
CREATE TABLE groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    created_by  BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_groups_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_groups_created_by ON groups (created_by);

CREATE TABLE group_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id  BIGINT       NOT NULL,
    user_id   BIGINT       NOT NULL,
    role      VARCHAR(20)  NOT NULL,
    joined_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_members_user  FOREIGN KEY (user_id)  REFERENCES users (id),

    -- Impide que un usuario aparezca dos veces en el mismo grupo, lo que
    -- duplicaria su parte en cada reparto.
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT ck_group_members_role CHECK (role IN ('ADMIN', 'MEMBER'))
);

CREATE INDEX idx_group_members_group ON group_members (group_id);
CREATE INDEX idx_group_members_user  ON group_members (user_id);

CREATE TABLE expenses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     BIGINT         NOT NULL,
    paid_by      BIGINT         NOT NULL,
    description  VARCHAR(200)   NOT NULL,
    amount       NUMERIC(12, 2) NOT NULL,
    category     VARCHAR(60),
    expense_date DATE           NOT NULL,
    created_at   TIMESTAMP(6)   NOT NULL,

    CONSTRAINT fk_expenses_group   FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_expenses_paid_by FOREIGN KEY (paid_by)  REFERENCES users (id),

    -- Un gasto de importe cero o negativo no tiene sentido y romperia el
    -- reparto (division por cero al calcular porcentajes).
    CONSTRAINT ck_expenses_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_expenses_group      ON expenses (group_id);
CREATE INDEX idx_expenses_paid_by    ON expenses (paid_by);
CREATE INDEX idx_expenses_group_date ON expenses (group_id, expense_date DESC);

CREATE TABLE expense_splits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id  BIGINT         NOT NULL,
    user_id     BIGINT         NOT NULL,
    amount_owed NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_expense_splits_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_splits_user    FOREIGN KEY (user_id)    REFERENCES users (id),

    -- Un mismo usuario no puede tener dos partes del mismo gasto.
    CONSTRAINT uk_expense_splits_expense_user UNIQUE (expense_id, user_id),

    -- Cero es valido: con importes muy pequenos repartidos entre muchos,
    -- a algun participante le puede tocar 0.00. Negativo nunca.
    CONSTRAINT ck_expense_splits_amount_non_negative CHECK (amount_owed >= 0)
);

CREATE INDEX idx_expense_splits_expense ON expense_splits (expense_id);
CREATE INDEX idx_expense_splits_user    ON expense_splits (user_id);

CREATE TABLE settlements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT         NOT NULL,
    paid_by    BIGINT         NOT NULL,
    paid_to    BIGINT         NOT NULL,
    amount     NUMERIC(12, 2) NOT NULL,
    status     VARCHAR(20)    NOT NULL,
    settled_at TIMESTAMP(6),

    CONSTRAINT fk_settlements_group   FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_settlements_paid_by FOREIGN KEY (paid_by)  REFERENCES users (id),
    CONSTRAINT fk_settlements_paid_to FOREIGN KEY (paid_to)  REFERENCES users (id),

    CONSTRAINT ck_settlements_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_settlements_status CHECK (status IN ('PENDING', 'CONFIRMED')),

    -- Nadie se paga a si mismo: seria una transaccion sin efecto que
    -- ensuciaria el calculo de balances.
    CONSTRAINT ck_settlements_distinct_parties CHECK (paid_by <> paid_to)
);

CREATE INDEX idx_settlements_group   ON settlements (group_id);
CREATE INDEX idx_settlements_paid_by ON settlements (paid_by);
CREATE INDEX idx_settlements_paid_to ON settlements (paid_to);
