-- =====================================================================
-- V2 - Refresh tokens con rotacion y deteccion de reutilizacion
--
-- Notas de diseno:
--
-- * Se guarda el SHA-256 del token, nunca el token. Si alguien obtiene un
--   volcado de esta tabla no consigue ninguna sesion. No se usa bcrypt
--   porque el token es aleatorio de 256 bits: no hay superficie de fuerza
--   bruta que justifique el coste, y bcrypt se ejecutaria en cada refresco.
--
-- * family_id agrupa toda la cadena de tokens nacida de un mismo login.
--   Al rotar, el token nuevo hereda la familia del anterior. Si alguna vez
--   se presenta un token ya usado, significa que alguien tiene una copia:
--   se revoca la familia entera y ambos, victima y atacante, quedan fuera.
--   Es la recomendacion del RFC 9700 (OAuth 2.0 Security BCP) para clientes
--   que no pueden guardar un secreto.
--
-- * ON DELETE CASCADE sobre users: borrar la cuenta cierra sus sesiones.
-- =====================================================================

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    -- SHA-256 en hexadecimal: siempre 64 caracteres.
    token_hash VARCHAR(64)  NOT NULL,
    family_id  UUID         NOT NULL,
    issued_at  TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),

    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_expiry CHECK (expires_at > issued_at)
);

CREATE INDEX idx_refresh_tokens_user   ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id);

-- Para la limpieza periodica de tokens caducados.
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);
