-- =====================================================================
-- V3 - Invitaciones a grupos mediante link con token
--
-- Notas de diseno:
--
-- * Igual que con los refresh token, se guarda el SHA-256 y nunca el token.
--   El link es la credencial: quien lo tenga entra al grupo, asi que un
--   volcado de esta tabla no debe bastar para colarse en ninguno.
--
-- * De un solo uso (accepted_at deja de ser NULL). Un link reutilizable
--   reenviado por error a un chat equivocado dejaria entrar a cualquiera de
--   forma indefinida. Para invitar a tres personas se generan tres links.
--
-- * email es opcional. Si esta relleno, solo esa direccion puede aceptar la
--   invitacion, de modo que reenviar el link a un tercero no sirve de nada.
--   Si es NULL, vale para quien lo reciba.
-- =====================================================================

CREATE TABLE invitations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT       NOT NULL,
    invited_by  BIGINT       NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL,

    -- Destinatario previsto. NULL = cualquiera con el link.
    email       VARCHAR(180),

    created_at  TIMESTAMP(6) NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,

    -- No nulos a la vez cuando la invitacion ya se consumio.
    accepted_at TIMESTAMP(6),
    accepted_by BIGINT,

    CONSTRAINT fk_invitations_group      FOREIGN KEY (group_id)    REFERENCES groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_invitations_invited_by FOREIGN KEY (invited_by)  REFERENCES users (id),
    CONSTRAINT fk_invitations_accepted_by FOREIGN KEY (accepted_by) REFERENCES users (id),

    CONSTRAINT uk_invitations_token UNIQUE (token_hash),
    CONSTRAINT ck_invitations_expiry CHECK (expires_at > created_at),

    -- Impide un estado a medias: aceptada sin saber por quien, o con un
    -- aceptante pero sin fecha.
    CONSTRAINT ck_invitations_accepted_consistent
        CHECK ((accepted_at IS NULL AND accepted_by IS NULL)
            OR (accepted_at IS NOT NULL AND accepted_by IS NOT NULL))
);

CREATE INDEX idx_invitations_group   ON invitations (group_id);
CREATE INDEX idx_invitations_expires ON invitations (expires_at);
